[package]
name = "chess-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess-core = { path = "../chess-core" }
raylib = "3.7"
rscenes = { version = "1.4.2", features = ["ecs", "eyre", "hecs"] }
